/*
 * Generated by VO Generator 
 */
package bxm.dft.smp.online.dbio.dto;

import bxm.common.annotaion.BxmCategory;
import bxm.vo.IValueObject;
import java.util.Collections;
import java.util.Hashtable;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * 
 *
 * @author sysadmin
 */
@SuppressWarnings("all")
@BxmCategory(type="VO", logicalName="", description="", author="sysadmin")
public class DSmpEmpTstVo000 implements IValueObject
{
	private static final long serialVersionUID= -190578417L;
	
	/**
	 * Row ID
	 */
	private java.lang.String rowId;
	/**
	 * Employee id
	 */
	private java.lang.Integer feduEmpNo;
	/**
	 * Employee name
	 */
	private java.lang.String feduEmpNm;
	/**
	 * Employee Occupy
	 */
	private java.lang.String feduOccpNm;
	/**
	 * Employee manager id
	 */
	private java.lang.Integer feduMngrEmpNo;
	/**
	 * Employee entering date
	 */
	private java.lang.String feduIpsaDt;
	/**
	 * Employee salary
	 */
	private java.math.BigDecimal feduPayAmt;
	/**
	 * Employee department
	 */
	private java.lang.Integer feduDeptNo;
	
	/**
	 * 
	 * @param rowId
	 */
	public void setRowId(java.lang.String rowId){
		this.rowId= rowId;
	}
	
	/**
	 * 
	 */
	public java.lang.String getRowId(){
		return rowId;
	}
	/**
	 * 
	 * @param feduEmpNo
	 */
	public void setFeduEmpNo(java.lang.Integer feduEmpNo){
		this.feduEmpNo= feduEmpNo;
	}
	
	/**
	 * 
	 */
	public java.lang.Integer getFeduEmpNo(){
		return feduEmpNo;
	}
	/**
	 * 
	 * @param feduEmpNm
	 */
	public void setFeduEmpNm(java.lang.String feduEmpNm){
		this.feduEmpNm= feduEmpNm;
	}
	
	/**
	 * 
	 */
	public java.lang.String getFeduEmpNm(){
		return feduEmpNm;
	}
	/**
	 * 
	 * @param feduOccpNm
	 */
	public void setFeduOccpNm(java.lang.String feduOccpNm){
		this.feduOccpNm= feduOccpNm;
	}
	
	/**
	 * 
	 */
	public java.lang.String getFeduOccpNm(){
		return feduOccpNm;
	}
	/**
	 * 
	 * @param feduMngrEmpNo
	 */
	public void setFeduMngrEmpNo(java.lang.Integer feduMngrEmpNo){
		this.feduMngrEmpNo= feduMngrEmpNo;
	}
	
	/**
	 * 
	 */
	public java.lang.Integer getFeduMngrEmpNo(){
		return feduMngrEmpNo;
	}
	/**
	 * 
	 * @param feduIpsaDt
	 */
	public void setFeduIpsaDt(java.lang.String feduIpsaDt){
		this.feduIpsaDt= feduIpsaDt;
	}
	
	/**
	 * 
	 */
	public java.lang.String getFeduIpsaDt(){
		return feduIpsaDt;
	}
	/**
	 * 
	 * @param feduPayAmt
	 */
	public void setFeduPayAmt(java.math.BigDecimal feduPayAmt){
		this.feduPayAmt= feduPayAmt;
	}
	
	/**
	 * 
	 */
	public java.math.BigDecimal getFeduPayAmt(){
		return feduPayAmt;
	}
	/**
	 * 
	 * @param feduDeptNo
	 */
	public void setFeduDeptNo(java.lang.Integer feduDeptNo){
		this.feduDeptNo= feduDeptNo;
	}
	
	/**
	 * 
	 */
	public java.lang.Integer getFeduDeptNo(){
		return feduDeptNo;
	}
	/*
	 * Dynamic Getter Setter
	 */
	private Hashtable<String, Object> htDynamicVariable= new Hashtable<String, Object>();
	
	@Override
	public Object get(String key){
		switch( key.hashCode() ){
		case 108704917 : /* rowId */
			return getRowId();
		case -2068798215 : /* feduEmpNo */
			return getFeduEmpNo();
		case -2068798217 : /* feduEmpNm */
			return getFeduEmpNm();
		case 568465552 : /* feduOccpNm */
			return getFeduOccpNm();
		case 716301837 : /* feduMngrEmpNo */
			return getFeduMngrEmpNo();
		case 409158357 : /* feduIpsaDt */
			return getFeduIpsaDt();
		case 595858864 : /* feduPayAmt */
			return getFeduPayAmt();
		case 255783062 : /* feduDeptNo */
			return getFeduDeptNo();
		default :
			if ( htDynamicVariable.containsKey(key) ) return htDynamicVariable.get(key);
			else {
				return null;
			}
		}
	}
	
	@SuppressWarnings("unchecked")
	@Override
	public void set(String key, Object value){
		switch( key.hashCode() ){
		case 108704917 : /* rowId */
			setRowId((java.lang.String) value);
			break;
		case -2068798215 : /* feduEmpNo */
			setFeduEmpNo((java.lang.Integer) value);
			break;
		case -2068798217 : /* feduEmpNm */
			setFeduEmpNm((java.lang.String) value);
			break;
		case 568465552 : /* feduOccpNm */
			setFeduOccpNm((java.lang.String) value);
			break;
		case 716301837 : /* feduMngrEmpNo */
			setFeduMngrEmpNo((java.lang.Integer) value);
			break;
		case 409158357 : /* feduIpsaDt */
			setFeduIpsaDt((java.lang.String) value);
			break;
		case 595858864 : /* feduPayAmt */
			setFeduPayAmt((java.math.BigDecimal) value);
			break;
		case 255783062 : /* feduDeptNo */
			setFeduDeptNo((java.lang.Integer) value);
			break;
		default :
			htDynamicVariable.put(key, value);
		}
	}
	
	/**
	 * Map for the declared fields and classes
	 */
	public static final Map<String, Class<?>> FIELDS;
	static{
		Map<String, Class<?>> temp= new LinkedHashMap<String, Class<?>>();
		temp.put("rowId", java.lang.String.class);
		temp.put("feduEmpNo", java.lang.Integer.class);
		temp.put("feduEmpNm", java.lang.String.class);
		temp.put("feduOccpNm", java.lang.String.class);
		temp.put("feduMngrEmpNo", java.lang.Integer.class);
		temp.put("feduIpsaDt", java.lang.String.class);
		temp.put("feduPayAmt", java.math.BigDecimal.class);
		temp.put("feduDeptNo", java.lang.Integer.class);
		FIELDS= Collections.unmodifiableMap(temp);
	}
	
	/**
	 * Map for the declared fields and objects
	 */
	@Override
	public Map<String, Object> getFieldValues(){
		Map<String, Object> map= new LinkedHashMap<String, Object>();
		map.put("rowId", getRowId());
		map.put("feduEmpNo", getFeduEmpNo());
		map.put("feduEmpNm", getFeduEmpNm());
		map.put("feduOccpNm", getFeduOccpNm());
		map.put("feduMngrEmpNo", getFeduMngrEmpNo());
		map.put("feduIpsaDt", getFeduIpsaDt());
		map.put("feduPayAmt", getFeduPayAmt());
		map.put("feduDeptNo", getFeduDeptNo());
		return map;
	}
}
